### ISSUE TITLE
Wither Skeletons and SafariNets - zC 0.0.11 

### ISSUE THREAD

**Issue by Rader2146** [warezit/zitCraft#18]
Capturing a wither skeleton in a safari net turns the wither skeleton into a normal skeleton.

**Comment by warezit** [comment]
Use "spawn exact copy" in the auto-spawner.

More details here: http://www.reddit.com/r/feedthebeast/comments/20dg77/wither_skull_farm/

**Comment by Rader2146** [comment]
I'm not trying to use the auto-spawner....I cant even get that far.  If I capture the wither skeleton and release is even 1 second later and still in the nether it's turned back into a regular skeleton.

**Comment by warezit** [comment]
That is normal, as far as I know.

The only way to release the wither skelly from a safari net is using the auto-spawner, with exact-copy mode turned on. If you release it any other way, it just spawns a normal skelly.

Feel free to correct me if I am wrong. This is just the way I understand the mechanics of it.

**Comment by Rader2146** [comment]
I first found the problem using the Auto-Spawner.  Capture skeleton, put in spawner, spawn exact copy was on, yet it spawns normal skeletons.  When you release a mob from the safari net it should always release the exact mob you picked up, spawning new mobs is when the exact copy comes into play.

Even the tooltip that would normaly say:
SafariNet (Re-Usable)
Wither Skeleton
Health: 20

After capturing it says:
SafariNet (Re-Usable)
Skeleton
Health: 20.0

**Comment by warezit** [comment]
> I first found the problem using the Auto-Spawner. Capture skeleton, put in spawner, spawn exact copy was on, yet it spawns normal skeletons.

Odd. Not sure why this is happening. This is the correct way to spawn Wither Skells, using an Auto-Spawner, as far as I understand.

> When you release a mob from the safari net it should always release the exact mob you picked up, spawning new mobs is when the exact copy comes into play.

Incorrect. Safari Nets have always had this issue with Skellys/Wither Skellys not spawning correctly. Because the "Wither Skelly" mob has the same base-ID as a regular Skelly, the same way colored sheep have the same base-ID as a regular sheep. The meta-data(NBT-data?) is what makes the difference between a Wither Skelly and a regular Skelly. Safari Nets will ALWAYS spawn regular Skellys, when you spawn them by-hand (without an auto-spawner, with exact-copy mode on).

This is what I see, when capturing a wither skelly on zC 0.0.12:
![image](https://cloud.githubusercontent.com/assets/8278779/6205376/5868cfa2-b531-11e4-8fba-f4f30661dc70.png)

Then I put that into an auto-spawner, and set exact copy to Yes:
![image](https://cloud.githubusercontent.com/assets/8278779/6205372/2ef7ff8a-b531-11e4-9e74-2a7b8db45cd4.png)

Then it spawns Wither Skellys just fine:
![image](https://cloud.githubusercontent.com/assets/8278779/6205370/288e031a-b531-11e4-956d-efcc7b3192ea.png)

**Comment by Rader2146** [comment]
I thought about the same thing with the sheep, and just tested with a black sheep and it works fine,  I always get a black sheep after picking up and placing down.

Just tested with wither's again:

![2015-02-15_14 49 53](https://cloud.githubusercontent.com/assets/10893728/6205410/111077b8-b522-11e4-9d0b-c1f09ed41e32.png)

![2015-02-15_14 50 03](https://cloud.githubusercontent.com/assets/10893728/6205412/18199b20-b522-11e4-97ac-2bae5db3cbd4.png)

**Comment by Rader2146** [comment]
Just notice that WAILA is saying:

Wither Skeleton
(HEARTS)
Ender IO

That's in both of our screenshots.

**Comment by warezit** [comment]
> I thought about the same thing with the sheep, and just tested with a black sheep and it works fine, I always get a black sheep after picking up and placing down.

Okay - well ignore my comment about the "sheep-thing"... But, what I said about Safari Nets and Wither Skells spawning regular Skellys still holds true.

> Safari Nets will ALWAYS (and always have) spawn regular Skellys, when you spawn them by-hand.

**Comment by warezit** [comment]
Well, I am not sure what resolved this issue, but I have tested this in zC 0.0.12, and it seems to be fixed.

I will be pushing out the next update (zC 0.0.12) shortly today.

**Comment by Rader2146** [comment]
sounds good, finders crossed.
