### ISSUE TITLE
Other Dimension Bugginess - zC 0.0.21

### ISSUE THREAD

**Issue by Benjaminjex** [warezit/zitCraft#32]
When I go to another dimension (Mining World, Spectre Dimension) it will load for 30 seconds or so, and then all the blocks will disappear from the screen, and I cannot interact with what should be there.

**Comment by zunzibarr** [comment]
The same happens in the end. Might be due to flying - but all blocks will disappear, I can see Enderman standing as if they're on floating islands, but no blocks are rendered and I am unable to move. As you remember, me logging off basically meant crashing until I was forcibly moved out of the dimension - Ender-Porter'ing out works though.

**Comment by warezit** [comment]
Just tried going to the End and to the Mining World, and both seem to work fine for me.

Give it a try again, and let me know if you have any issues.

**Comment by warezit** [comment]
I "think" this is fixed after I cleaned up the server/world file a bit; let me know here if you run into this again.

**Comment by Benjaminjex** [comment]
It's Back. Tried the Mining Dimension. Tried the Twighlight Forest. Succeeded with the spectre dimension but who knows how long that will last.
