### ISSUE TITLE
Zc2.0 - Extra utilities iron spikes crashing client

### ISSUE THREAD

**Issue by Unyieldingvenom** [warezit/zitCraft#35]
Went to make an iron spike and it crashed my client as soon as I put the last item in the crafting table, logged back in and checked nei to see if the recipe had changed and the icon for the spike is just fire and trying to look at the recipe crashes the client again.

**Comment by Rader2146** [comment]
Please upload a crash log so we can see what's going on.

**Comment by Unyieldingvenom** [comment]
http://pastebin.com/yi4EmHWa

**Comment by warezit** [comment]
Thank you for uploading the log file!

This guy is having the same issue: https://github.com/rwtema/extrautilities/issues/575

Also, this appears to be fixed in ExtraUtils 1.2.4a: http://minecraft.curseforge.com/mc-mods/225561-extra-utilities/files/2233352 (scroll down for changelog)

Unfortunately, upgrading from EU 1.2.4 to 1.2.4a requires upgrading Forge from 1291 to 1355.

I'll try to upgrade Forge and see if that works/doesn't cause a whole new set of problems.

**Comment by warezit** [comment]
This issue is fixed in ExUtils 1.2.4b.

I have confirmed this is working on the zitCraft dev pack, and will be released in the next update: zC 2.0.2.
